on:
  workflow_dispatch:
   inputs:
    appenv:
      type: choice
      description: Choose the target environment
      options: 
        - dev
        - test
        - prod

name: Azure Bicep-Advanced
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: create resource group
      run: az group create --name ${{ secrets.AZURE_RG }} --location westeurope
      
      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=${{ github.event.inputs.appenv }}